### ISSUE TITLE
How to migrate away from 'nameof'?

### ISSUE THREAD

**Issue by zapta** [pwwang/python-varname#117]
We have a code similar to the one below where we use ``nameof`` to convert arg names to strings. The advantage is that the ide tools are aware of the relation between the function args and nameof's args (e.g. when renaming or linting).

We tried to upgrade to the latest varname version and get a warning that we should use argname() instead but it seems to require the name of the arg a a string which defeats the reason we use varname.

Are we missing anything?  What is the use case of argname() if the user requires to provide the arg name string? 

```
def cli(
    cmd_ctx: click.core.Context,
    # Options:
    ftdi_install: bool,
    ftdi_uninstall: bool,
    serial_install: bool,
    serial_uninstall: bool,
):
    """Implements the drivers command."""

    # User should select exactly on of these operations.
    cmd_util.check_exactly_one_param(
        cmd_ctx,
        nameof(ftdi_install, ftdi_uninstall, serial_install, serial_uninstall),
    )
```

**Comment by pwwang** [comment]
What do you think this will return:

`nameof(ftdi_install, ftdi_uninstall, serial_install, serial_uninstall)`?

**Comment by zapta** [comment]
I think

["ftdi_install", "ftdi_uninstall", 'serial_install", "serial_uninstall"]

That is, nameof maps arg references to arg names.

**Comment by pwwang** [comment]
So then why not just use `["ftdi_install", "ftdi_uninstall", 'serial_install", "serial_uninstall"]` directly?

**Comment by zapta** [comment]
Because the IDE and tools like linters will not be aware of the association
between the arg ``ftdi_install`` and the string ``'ftdi_install'``. For
example if we rename the arg of if the string has a typo.

**Comment by zapta** [comment]
Because the IDE and tools like linters will not be aware of the association
between the arg ``ftdi_install`` and the string ``'ftdi_install'``. For
example if we rename the arg of if the string has a typo.

**Comment by pwwang** [comment]
I don't get it. If you change, say, `ftdi_install` to `ftdi_install2`, then what will the IDE/linters complain about if you do:

```python
def cli(
    cmd_ctx: click.core.Context,
    # Options:
    ftdi_install2: bool,
    ftdi_uninstall: bool,
    serial_install: bool,
    serial_uninstall: bool,
):
    """Implements the drivers command."""

    # User should select exactly on of these operations.
    cmd_util.check_exactly_one_param(
        cmd_ctx,
        ["ftdi_install2", "ftdi_uninstall", "serial_install", "serial_uninstall"),
    )
```

**Comment by zapta** [comment]
The tools will not complain that there is no arg called ``ftdi_install3``, but with nameof() they will.  Same if I use an IDE refactoring tool to rename the arg ``ftdi_uninstall`` to ``ftdi_install4``, it will not rename also the string ``ftdi_uninstall``, but with nameof() it will.

```
def cli(
    cmd_ctx: click.core.Context,
    # Options:
    ftdi_install2: bool,
    ftdi_uninstall: bool,
    serial_install: bool,
    serial_uninstall: bool,
):
    """Implements the drivers command."""

    # User should select exactly on of these operations.
    cmd_util.check_exactly_one_param(
        cmd_ctx,
        ["ftdi_install3", "ftdi_uninstall", "serial_install", "serial_uninstall"),
    )
```

**Comment by pwwang** [comment]
I am still confused. Why did you put `"ftdi_install3"` instead of `"ftdi_install2"`?

**Comment by zapta** [comment]
To demonstrate a mismatch (e.g. a typo) between the arg name and the string. If instead of ``"ftdi_install3"`` I use ``nameof(ftdi_install3)``, then the tools detect the error statically, in the editor.

**Comment by pwwang** [comment]
I see what you meant. But I am not convinced that `nameof` should be used for this purpose. But if you do want it to be used this way, you can wrap a version of `nameof` by yourself using `argname`:

```python
from varname import argname

def my_nameof(*args):
  return argname('*args')

a = b = 1
my_nameof(a, b)  # ('a', 'b')
```

**Comment by zapta** [comment]
You can look at the code in the link below. All the places that argument ``fix`` is mentioned are associated with each other and if I rename one they all change. With strings they are isolated from each other and the tools don't know about the intended association.


https://github.com/FPGAwars/apio/blob/ca5dc994ff7f66b1f752db57bfad3b97a0eb0772/apio/commands/packages.py#L222

**Comment by pwwang** [comment]
What you referred to as "associated" or "isolated" is merely due to the help of the IDE, rather than being based on the code itself.

**Comment by zapta** [comment]
Thanks! I will give it a try.

I believe that they are associated by the semantics of python, because they
are two references to the same semantic construct. On the other hand, two
variables x in different functions are considered independent of each
other. The tools just follow the semantic of the language.

**Comment by pwwang** [comment]
You are correct, and that is the foundation of the IDE. I won’t argue about code style. However, `nameof` has been deprecated due to its redundancy with `argname`, and it's quite straightforward to implement it using `argname` (as I demonstrated in the above example). Another reason for the deprecation is that many people tend to use it incorrectly. In many cases, literal strings are sufficient.

**Comment by zapta** [comment]
I implemented ``my_nameof`` and it works, thanks.

I just had to rename ``args`` to ``_args`` to make the tools happy since from their perspective it's an unused argument.

**Comment by mizraith** [comment]
> I see what you meant. But I am not convinced that `nameof` should be used for this purpose. But if you do want it to be used this way, you can wrap a version of `nameof` by yourself using `argname`:
> 
> from varname import argname
> 
> def my_nameof(*args):
>     return argname('*args')
> 
> a = b = 1
> my_nameof(a, b)  # ('a', 'b')

**NOTE:  The above example does not work for us.**

Also --- the decision to remove nameof() is highly unfortunate and I will explain why.

-----
First off -- here is a simplifed example of why we use and love "nameof()" in our project. Let's start by creating a few simple classes with a class variable.  This is very contrived.
```
class MyWeight:
    val = 75

class MyHeight:
   val = 72
```

or use a dataclass (which are extremely convenient)
```
from dataclasses import dataclass
@dataclass
class MyWeight:
    val: float = 75

@dataclass
class MyHeight:
    val: float =72
```
    
**With nameof()**    (varname < 0.14)  we could do something highly descriptive like this:
`    my_dictionary[nameof(MyWeight.val)] = 35`


Instead of the **brittle magic-string approach** where val could be many things:
`my_dictionary['val'] = 35`
 

Given the above, _what happens when (in a large project with a hundred source files) we want to change MyWeight.val  --> MyWeight.val_kg   without impacting MyHeight ?_

*  With **nameof()** we use the IDE to refactor variable x and all instances where MyWeight.val is used are quickly and painless renamed to MyWeight.val_kg  but leave alone places where MyHeight.val is used.

*  However, without nameof(), on has to search the same hundreds of files on the string "val" or  '"val"' and, well, may the powers have mercy on your soul.   Much riskier and absolutely prone to partial refactors.    


Given the importance of nameof(), I have tried the implementation quoted above and it doesn't work (python 3.11, varname 0.14.0)

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2024.3.1.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "<input>", line 2, in nameof
  File "C:\Users\red.byer\!!CODE\AET_Eagle\.mqttbasevenv\Lib\site-packages\varname\core.py", line 328, in argname
    raise VarnameRetrievingError(
varname.utils.VarnameRetrievingError: Cannot retrieve the node where the function is called.
```

Is there a better, working example for argname?    Was there really a cost associated with keeping the nameof() interface if it really only represents 2 lines of code?

**Comment by pwwang** [comment]
I don't quite understand why changing `MyWeight.val_kg` affects `MyHeight`? If you just want to please the IDE, you can just use a variable, say `val_name` to store `"val"`:

```python
val_name = "val"

# your class definition

my_dictionary[val_name] = 35
```

**Comment by pwwang** [comment]
@mizraith You also mentioned that the implementation of `nameof()` didn't work. Can you try to save it to a python file and run it with `$ python name-of-implementation.py`?

**Comment by zapta** [comment]
For the record, we had to drop  the usage of varname because it didn't work with pyinstaller.

https://github.com/orgs/pyinstaller/discussions/9025

**Comment by pwwang** [comment]
@zapta You are correct. We need the source code to trace the AST node. However, PyInstaller does not include the source code with the compiled app.

**Comment by mizraith** [comment]
I'm pretty sure I got nameof() to work within a packaged app installed by pyinstaller (there are other gripes about the state of pyinstaller outside the scope of this conversation).   

Question 1:   "How is changing *MyWeight.val* impacting *MyHeight.val*?
   A few ways to explain this:
              If somewhere among the soup of project files, all we use is the string "val" as our dictionary key, this provides a lot less information than *nameof(MyWeight.val)*.     When I go to update the parameters in the *MyWeight* class, having "val" linked to its class name makes it unique (MyWeight.val is different than MyHeight.val).   On the other hand, if we just use magic strings, like "val" we know have to decide each time across dozens of uses which cases are MyWeight and which cases are MyHeight.   This is not about making the IDE happy, it's about making refactoring a much safer operation.
        So, why do we get into this pickle?   Dataclasses naturally flow between dictionaries and JSON representations. When doing this (again, large project), it helps to reference the unique classname.parm  (*MyHeight.val*).    If we change the parameter to *MyHeight.val_in*, then it gets updated even in the nameof() dictionary usages, which means that the flow between the dictionary and back into a class happens without a problem.     If instead we have magic strings and miss one, an old dictionary key ("val") will no longer properly map into the updated *MyHeight.val_in*.
         Remember...big project.   The word "val" might appear in 8 different classes spread across dozens of source file.   Refactoring "val" to "val_mm" and getting it correct is difficult.   Leveraging the IDE is absolutely in our interest in this case, and nameof() is our friend.  PyInstaller...less so (especially with the pitiful documentation and nasty attitude of the maintainers on their forums -- good luck figuring out pre and post install hooks).

I'll try to build up the nameof example file right now (using 0.14 and argname)

**Comment by pwwang** [comment]
> I'm pretty sure I got nameof() to work within a packaged app installed by pyinstaller (there are other gripes about the state of pyinstaller outside the scope of this conversation).

There was a chance for `nameof` to function without source code, using bytecode; however, this is only applicable in very straightforward cases. But you will have no luck with `argname()` or `varname()`, or maybe use some hooks (I didn't try any of those).

> 
> Question 1: "How is changing _MyWeight.val_ impacting _MyHeight.val_? 
> A few ways to explain this: If somewhere among the soup of project files, all we use is the string "val" as our dictionary key, this provides a lot less information than _nameof(MyWeight.val)_. When I go to update the parameters in the _MyWeight_ class, having "val" linked to its class name makes it unique (MyWeight.val is different than MyHeight.val). 

I am still confused. When you describe your example, can you be more specific? For example, "When I go to update the parameters in the _MyWeight_ class", which parameters are you exactly talking about? "MyWeight.val is different than MyHeight.val", do you mean their values? or when used as dictionary keys?

> On the other hand, if we just use magic strings, like "val" we know have to decide each time across dozens of uses which cases are MyWeight and which cases are MyHeight. This is not about making the IDE happy, it's about making refactoring a much safer operation. 

"which cases are MyWeight and which cases are MyHeight." When were they mixed or messed up?

> So, why do we get into this pickle? Dataclasses naturally flow between dictionaries and JSON representations. When doing this (again, large project), it helps to reference the unique classname.parm (_MyHeight.val_). If we change the parameter to _MyHeight.val_in_, then it gets updated even in the nameof() dictionary usages, which means that the flow between the dictionary and back into a class happens without a problem. 

So when you change  your `MyHeight` to:

```python
class MyHeight:
	val_in = 35
```
When referring to the value, you also have to change `d[nameof(MyHeight.val)]` to `d[nameof(MyHeight.val_in)]`, right?

> If instead we have magic strings and miss one, an old dictionary key ("val") will no longer properly map into the updated _MyHeight.val_in_. Remember...big project. The word "val" might appear in 8 different classes spread across dozens of source file. 
> Refactoring "val" to "val_mm" and getting it correct is difficult. 

So confused about this refactoring. Again, if you refactor `val` to `val_mm` in you class definition, when referring to it, even with `nameof`, you still have to change `nameof(MyHeight.val)` to `nameof(Myheight.val_mm)` right?

> Leveraging the IDE is absolutely in our interest in this case, and nameof() is our friend. PyInstaller...less so (especially with the pitiful documentation and nasty attitude of the maintainers on their forums -- good luck figuring out pre and post install hooks).

I'd be happy to see some experiments about this.

> 
> I'll try to build up the nameof example file right now (using 0.14 and argname)

Looking forward to seeing a more clear example.

**Comment by mizraith** [comment]
FIRST:  for those paying attention, in order to mimic nameof() in varname 0.14, I used the following function:

```python
def nameof(args):
     return argname('args')
```
This returns a string value for the arg.   Whereas the prior example returns  a list -> ('name',)   

SECOND:
    Attached is a contrived and over simplified example that demonstrates the challenge in a singular file.  Imagine this packing/unpacking between dictionaries and json is happening in very different files.  

 **I almost forgot to mention the value of auto-completion.** Imagine dealing with lots of different classes.  I'll take autocomplete  -> "MyHeight.value..."  versus a guess at a magic string (was it "value" or "val" or "value_m" or "value_in", what are my options?)

BELOW
Find/Replace refactoring on magic strings is....risky and time consuming.  You can try for yourself by find/replace "value" to "value_kg".   If you miss the first set of magic strings or get the wrong one, you won't be able to rebuild the data class and the except clause will be called.  Don't forget to find replace around line 31/32 as well.

On the other hand, if you use nameof() and maintain a firm link to the class parameter, the refactoring is much easier.   A modern IDE makes it almost foolproof because it even catches the parameter names in the original init function (lines 31:32).    A string find/replace  on "MyWeight.value" -> "MyWeight.value_kg" will be only partially successful as it will miss 31/32.

-----------------------------------
```python
from varname import argname
from dataclasses import dataclass
from pprint import pformat
import json


# The following is the recommended implementation based on: https://github.com/orgs/pyinstaller/discussions/9025
# But this returns a tuple:    nameof(MyWeight.value) -->  ('value',)
# def nameof(*args):
#   return argname('*args')

# This version returns a string using varname 0.14
def nameof(arg):
  return argname('arg')



@dataclass
class MyWeight:
  value: float = 0.0
  val: float = 0.0

@dataclass
class MyHeight:
  value: float = 0.0
  val: float = 0.0



if __name__ == '__main__':
  print("\nnameof() results:")
  print(f"\tnameof(MyHeight.value) => {nameof(MyHeight.value)}")
  print(f"\tnameof(MyWeight.value) => {nameof(MyWeight.value)}\n")

  mw = MyWeight(value=100.0, val=200.0)
  mh = MyHeight(value=3.0, val=72.0)

  mw_d = mw.__dict__
  mw_j = json.dumps(mw.__dict__)
  mh_d = mh.__dict__
  mh_j = json.dumps(mh.__dict__)
  print(f"MyWeight as a\n\tdict: { pformat(mw_d) }\n\tjson: {mw_j}")
  print(f"MyHeight as a\n\tdict: { pformat(mh_d) }\n\tjson: {mh_j}")

  # ---------------------------------------------------------------------------
  # now imagine we just sent and received that json and want to re-build it as a class
  # This code would be disconnected in some other module
  incoming_json = mw_j
  incoming_dict = json.loads(incoming_json)

  # RECREATING WITH A MAGIC STRING PRE-TEST
  try:
    if "value" in incoming_dict.keys():
      # we think this is a MyHeight?d
      incoming_mh = MyHeight(**incoming_dict)
      print(f"\nUSING MAGIC STRING\tincoming_mw: {incoming_mh}")
    if "value" in incoming_dict.keys():
      # or it could be a MyWeight
      incoming_mw = MyWeight(**incoming_dict)
      print(f"USING MAGIC STRING\tincoming_mw: {incoming_mw}")
  except Exception as e:
    # NOTE, if you refactor line 12, changing MyWeight.value -> MyWeight.value_kg.  This is easy
    # for this singular file.  Now imagine we have many of these dataclasses used by many people in
    # dozens of different files.  Very easy to miss a string refactor somewhere with a string search.
    # The above dictionary->class conversion will break.
    # If you refactored incompletely, You may either miss the conversion or throw a "MyHeight.__init__() got an unexpected keyword argument 'value_kg'
    print(e)

  # RECREATING WITH A NAMEOF PRE-TEST
  try:

    # NOTE:  Another benefit is that most IDEs will give you autocomplete.  After refactoring
    # as you start to type ".value..."  it will hint you to use "value_kg" for instance.
    if nameof(MyHeight.value) in incoming_dict.keys():      # <<< THIS WORKS with varname 0.13
      # we think this is a MyHeight?d
      incoming_mh = MyHeight(**incoming_dict)
      print(f"\nUSING NAMEOF\tincoming_mw: {incoming_mh}")
    if nameof(MyWeight.value) in incoming_dict.keys():
      # or it could be a MyWeight
      incoming_mw = MyWeight(**incoming_dict)
      print(f"USING NAMEOF\tincoming_mw: {incoming_mw}")
  except Exception as e:
    # The above will not fail as standard refactoring and the intention is much more clear than the magic string version
    print(e)

```

Running the above with 0.14 gives the result:
```
nameof() results:
	nameof(MyHeight.value) => value
	nameof(MyWeight.value) => value

MyWeight as a
	dict: {'val': 200.0, 'value': 100.0}
	json: {"value": 100.0, "val": 200.0}
MyHeight as a
	dict: {'val': 72.0, 'value': 3.0}
	json: {"value": 3.0, "val": 72.0}

USING MAGIC STRING	incoming_mw: MyHeight(value=100.0, val=200.0)
USING MAGIC STRING	incoming_mw: MyWeight(value=100.0, val=200.0)

USING NAMEOF	incoming_mw: MyHeight(value=100.0, val=200.0)
USING NAMEOF	incoming_mw: MyWeight(value=100.0, val=200.0)
```

We can argue at different ways to achieve this dataclass->json->dataclass and why we might do it certain ways.  Suffice to say that I have left many details out and there are much more complex examples and iterators.   Keeping the magic strings out of the situation has absolutely helped us scale the project and reduced refactoring errors significantly.   Nobody can predict the best parameter name perfectly, so refactoring is a reality.  Hence our reliance on varname.nameof()

**Comment by pwwang** [comment]
@mizraith 

I believe this is more of a design topic to discuss. While I still think that `nameof()` isn't necessary in this scenario, it's perfectly fine if you prefer to use it. You can implement your own version based on the example I provided. 

Let's continue our discussion about implementing your own `nameof`.

`my_nameof(*args)` returns a tuple because it accepts multiple arguments. If you want to restrict it to a single argument, your implementation is preferable.

If more developers argue about this in the future, I would prefer to bring it back in, but under the `varname.helpers` module.

**Comment by mizraith** [comment]
Agreed it's not necessary, but it absolutely makes project management much better on a large evolving code base.    From direct experience, nameof has saved us countless hours of debugging.    The one downside we have seen is speed (nameof is not the fastest tool), but so long as we aren't calling it thousands of time per second we do fine.

The basic implementation (shown) works fine for us.  We don't need the flexibility and overloading provided.    In the coming months will see if there is a way to bend pyinstaller to our will.

**Comment by zapta** [comment]
@alelom, you can implement your varname package based on this one, using the simple function at https://github.com/pwwang/python-varname/issues/117#issuecomment-2558351368

@pwwang, you may want to consider adding it back since there is clearly a demand for.

**Comment by alexmojaki** [comment]
@pwwang I archived https://github.com/alexmojaki/nameof and directed people to varname a while ago. I was also surprised to learn that nameof was deprecated here. Is the problem that the bytecode version stopped working in newer versions and was too hard to maintain?

**Comment by pwwang** [comment]
I can't find all the ones that I saw, but here is a typical one:

https://github.com/mitdbg/logos/blob/a6a0b60d2e15d8abc08471f148b1c97d8845ca34/src/logos/logos.py#L310-L314

```python
        parsed_df_names = [
            nameof(self._parsed_log),
            nameof(self._parsed_templates),
            nameof(self._parsed_variables),
        ]
```
This either will not give the names expected, or it is not even necessary.

**Comment by alexmojaki** [comment]
That looks like correct usage to me.

Was there a different kind of usage for nameof that you expected or considered correct?

**Comment by alelom** [comment]
@alexmojaki >this is a problem

Thanks for raising! Although I'd rather have these comments directly as issues in the repo, rather than here.

Fixed in https://github.com/alelom/python-nameof/pull/2.

**Comment by pwwang** [comment]
`nameof` is back at [`v0.15.0`](https://github.com/pwwang/python-varname/releases/tag/0.15.0)
